"""
main.py
--------
FastAPI application entrypoint for the AI Medical Report Explainer.

Run with:
    uvicorn main:app --reload --port 8000
"""

import logging

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded

from models.database import init_db
from routes import auth, upload, analysis, history

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("main")

# --- Rate limiter (protects auth & upload endpoints from abuse) ---
limiter = Limiter(key_func=get_remote_address, default_limits=["100/hour"])

app = FastAPI(
    title="AI Medical Report Explainer API",
    description=(
        "Upload medical reports and get simple-language AI explanations. "
        "This API is for educational purposes only and does not provide "
        "medical advice."
    ),
    version="1.0.0",
)

app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

# --- CORS: allow the local static frontend to call this API ---
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://127.0.0.1:5500",
        "http://localhost:5500",
        "http://127.0.0.1:5501",
        "http://localhost:5501",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.on_event("startup")
def on_startup():
    """Creates database tables if they don't already exist."""
    init_db()
    logger.info("Database initialized. AI Medical Report Explainer API is ready.")


@app.get("/", tags=["Health"])
def root():
    return {
        "status": "ok",
        "service": "AI Medical Report Explainer API",
        "disclaimer": (
            "This explanation is generated by AI and is for educational "
            "purposes only. It is NOT medical advice. Please consult a "
            "qualified doctor."
        ),
    }


@app.get("/dashboard", tags=["Health"])
def dashboard_health():
    """Lightweight endpoint the frontend dashboard can ping to verify connectivity."""
    return {"status": "ok"}


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    logger.exception("Unhandled error on %s", request.url)
    return JSONResponse(
        status_code=500,
        content={"detail": "An unexpected server error occurred. Please try again."},
    )


# --- Routers ---
app.include_router(auth.router)
app.include_router(upload.router)
app.include_router(analysis.router)
app.include_router(history.router)
